name: "Standard"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest
    env:
      api-dir: ./

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Standard checks
      working-directory: ${{env.api-dir}}
      run: bundle exec standardrb
